### PR TITLE
Update Match model

### PR DESCRIPTION
**Pull request by nicbavetta**
I have updated this model per the the latest spec.

See additional details [here](https://github.com/dougdellolio/coinbasepro-csharp/issues/198#issuecomment-774482786).

### CODE REVIEW

**Comment by dougdellolio** [comment]
awesome, thank you!

**Comment by nicbavetta** [comment]
> awesome, thank you!

No problem. Can we push an updated NuGet package to make use of these changes?

**Comment by dougdellolio** [comment]
@nicbavetta done. Please update to latest version on NuGet

**Comment by nicbavetta** [comment]
> @nicbavetta done. Please update to latest version on NuGet

@dougdellolio Got it, thanks!

**Pull request merged**
