### PR TITLE
[Feature] Add unknown types to handle new Product Types and Currencies

### PR DESCRIPTION
**Pull request by dougdellolio**
This PR aims to handle the case when Coinbase adds new product types and currencies. Currently an error is thrown because it can't properly deserialize the types.

### CODE REVIEW

**Comment by chrisw000** [comment]
This would leave **any** de-serialization issues as handled... which could have unknown effects depending on whatever it was that failed to de-serialize?

is it possible to only mark as handled when the object in question is Currency or ProductType?

**Comment by dougdellolio** [comment]
yeah that is the biggest downside to this "fix" currently. The problem with checking for type only here is the type that gets returned in `ErrorEventArgs` isn't the enum but rather the object that holds the ProductType or Currency which means we would have to match on everything that holds these two types. I don't see of any way to get match other than looking at the message (feels super hacky). 

Any ideas around that?

**Comment by chrisw000** [comment]
Possible have a custom converter for the enum, so that it falls back to "unknown", and therefore doesn't actually throw an error in the first place? The error logging could still happen when it's being set to unknown in the custom converter?

Something like this:
https://github.com/JamesNK/Newtonsoft.Json/issues/1361

https://stackoverflow.com/questions/22752075/how-can-i-ignore-unknown-enum-values-during-json-deserialization

**Comment by dougdellolio** [comment]
@chrisw000 please take a look. I have used part of the implementation from above and removed some bits that I don't think are needed. I can't see anything wrong with it.

Also I have added a log error in the converter. All tested using the new one that was just added last night (USDC)
https://github.com/dougdellolio/coinbasepro-csharp/pull/164/files#diff-41981c1d2c619727aa999f941c4d6f88R65

here is how it would look:
capture

**Pull request merged**
