### PR TITLE
Feature/timestamp server

### PR DESCRIPTION
**Pull request by linpiero**
Hi,
I made this change to indicate to the library (via an optional parameter) to mark the request with the timestamp returned by the service https://docs.gdax.com/#time, use:
`//create an authenticator with your apiKey, signature and passphrase
var authenticator = new Authenticator("<apiKey>", "<signature>", "<passphrase>");

//create the GDAX client
var gdaxClient = new GDAXClient.GDAXClient(authenticator, useServerTime:true);

//use one of the services 
var allAccounts = await gdaxClient.AccountsService.GetAllAccountsAsync();`

with this version I do not have the error: "request timestamp expired"

### CODE REVIEW

**Comment by dougdellolio** [comment]
perhaps we should not even give the option and just always use server time. what do you think?

**Comment by linpiero** [comment]
Hi,
I answer you questions:
_Is there a more than 30 second time gap from when you are getting the time to when you are sending the request?_
yes my local time is out of 2 minutes and that's why I get the error
_perhaps we should not even give the option and just always use server time. what do you think?_
for the moment I would leave the optional parameter because so far I am the only one to have the problem :-)
also there is the rate limit to be considered (https://docs.gdax.com/#rate-limits), in my code to call your library I use "https://github.com/David-Desmaisons/RateLimiter"
Thanks!

**Comment by dougdellolio** [comment]
This problem feels very specific and I am not convinced it should be a part of the library just yet. If you don't mind I would like to keep this PR open for a while to see how others react to it too. If I see this issue becoming very common then I think it would be great to add.

Thanks!

**Comment by linpiero** [comment]
ok I agree with you. 👍 
Thank you very much

**Comment by alexhiggins732** [comment]
I have experienced this issue in the past on a few occasions. For whatever reason my local system clock was running slow and was not being updated. In my opinion, for applications that use this DLL in their own client facing products this would be a nice feature to have. Otherwise client applications which have out of sync system clocks will experience errors.

**Comment by linpiero** [comment]
Hello @alexhiggins732,
I had created this PR because the clock on my pc was not synchronized and so I changed the logic so that before each call the server time is passed.
I later suspended and in the meantime I solved this way:
- I created a powershell script that manually syncs the PC clock via the internet
- I created a windows task that runs every 5 minutes
In this way, using the library on the master branch, I have no more errors

**Pull request closed without merging**
