### PR TITLE
GetChannels Subscription Fix

### PR DESCRIPTION
**Pull request by alexhiggins732**
Fix GetChannels to return only the channels specified in channelTypes. Current codes returns all channels defined in CoinbasePro.WebSocket.Types.ChannelType.

### CODE REVIEW

**Comment by dougdellolio** [comment]
@alexhiggins732 can you explain more the problem this is trying to solve?

**Comment by alexhiggins732** [comment]
@dougdellolio With the current code, no matter what channel (s) you pass to `WebSocket.Start()` to you are subscribed to all channels channels defined in CoinbasePro.WebSocket.Types.ChannelType (Full, Heartbeat, Level2, Matches, Ticker, User).

For example, if you try to pass just the user channel or just the ticker channel you are still subscribed to all channels. 

The reason is because the following if statement always fires: `if (channelTypes == null || channelTypes.Any())`


If you don't pass any channel types the left hand side of || operator first. If you do the right hand side evaluates to true because channelTypes.Any() evaluates to true. So in either case ( when you don' supply channels or you do) the result is you are subscribed to `foreach (ChannelType channelType in Enum.GetValues(typeof(ChannelType)))`


The if statement should only be entered if the no channels where specified (channelTypes==null) or an empty list was supplied (channelTypes.Count==0). In any other case the else statement should fire because a non-empty list of channels was passed to `Start` in which case the WebSocket subscribes to the channels specified in channelTypes.

**Comment by alexhiggins732** [comment]
Will have to look at the tests to see why they fail now. Hopefully will be have an update later tonight.

**Comment by alexhiggins732** [comment]
The test specs were passing the L2 channel to all of the function but the assertions were that subscription message would include all channels. Everyone of these tests should have failed if not for the original bug which is now passed.

I fixed this issue by coding the specs to correctly send an empty channel list to all tests and additionally added specs to correctly test send messages contained only specified channels.

**Comment by dougdellolio** [comment]
excellent. thanks @alexhiggins732!

**Pull request merged**
